#![no_std]

#[cfg(test)]
mod test;


use soroban_sdk::{
    contract, contractimpl, contractevent, token, Address, BytesN, Env,
};

/// Event emitted when a new stealth deposit is made.
#[contractevent(topics = ["stealth", "deposit"])]
pub struct StealthDepositEvent {
    /// The ephemeral public key generated by the sender (used by receiver for ECDH)
    pub ephemeral_key: BytesN<32>,
    /// The XOR-encrypted 32-byte Stellar seed for the stealth address
    pub encrypted_seed: BytesN<32>,
    /// The resulting stealth address that controls the funds
    pub stealth_address: Address,
    /// Amount of token deposited
    pub amount: i128,
    /// Token address
    pub token: Address,
}

#[contract]
pub struct StealthContract;

#[contractimpl]
impl StealthContract {
    /// Deposit funds into the smart contract and assign them to a stealth address.
    pub fn deposit(
        env: Env,
        from: Address,
        stealth_address: Address,
        ephemeral_key: BytesN<32>,
        encrypted_seed: BytesN<32>,
        token: Address,
        amount: i128,
    ) -> bool {
        from.require_auth();

        if amount <= 0 {
            panic!("Amount must be greater than 0 (dummy hash change)");
        }

        // Transfer funds from sender to this contract
        let token_client = token::Client::new(&env, &token);
        token_client.transfer(&from, &env.current_contract_address(), &amount);

        // Update persistent storage for the stealth address
        let current_balance: i128 = env.storage().persistent().get(&stealth_address).unwrap_or(0);
        env.storage().persistent().set(&stealth_address, &(current_balance + amount));
        
        // Bump TTL to ensure the stealth deposit doesn't expire quickly (approx 30 days)
        env.storage().persistent().extend_ttl(&stealth_address, 518400, 518400);

        // Emit the event so the receiver can scan for it
        StealthDepositEvent {
            ephemeral_key,
            encrypted_seed,
            stealth_address,
            amount,
            token,
        }
        .publish(&env);
        
        true
    }

    /// Withdraw funds from a stealth address to a final destination.
    pub fn withdraw(
        env: Env,
        stealth_address: Address,
        token: Address,
        destination: Address,
        relayer: Address,
    ) {
        // The derived stealth address must authorize this withdrawal
        stealth_address.require_auth();

        let balance: i128 = env.storage().persistent().get(&stealth_address).unwrap_or(0);

        if balance <= 0 {
            panic!("No funds available for this stealth address");
        }

        // Zero out the balance to prevent re-entrancy/double withdrawal
        env.storage().persistent().remove(&stealth_address);

        // Calculate 0.5% fee
        // 0.5% is 5/1000
        let fee: i128 = (balance * 5) / 1000;
        let transfer_amount: i128 = balance - fee;

        let token_client = token::Client::new(&env, &token);

        // Transfer the 0.5% fee to the relayer
        if fee > 0 {
            token_client.transfer(&env.current_contract_address(), &relayer, &fee);
        }

        // Transfer the remaining funds to the specified destination
        if transfer_amount > 0 {
            token_client.transfer(&env.current_contract_address(), &destination, &transfer_amount);
        }
    }
}
